spring.application.name=usuarios

server.port=8081
app.frontend-base-url=${FRONTEND_BASE_URL:http://localhost:4200}
app.frontend.url=${FRONTEND_URL:http://localhost:4200}

email.api.url=${EMAIL_API_URL:https://api.brevo.com/v3/smtp/email}
email.api.key=${MAIL_API:${EMAIL_API_KEY:}}
email.sender.name=${EMAIL_SENDER_NAME:ESI Entradas}
email.sender.address=${MAIL_USER:${EMAIL_SENDER_ADDRESS:no-reply@example.com}}

# SQL Server instalado en Windows
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=esiusuarios;encrypt=true;trustServerCertificate=true
spring.datasource.username=usuarios_app
spring.datasource.password=usuarios_pwd
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update

server.error.include-message=always

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
